# Generated by Django 3.0.4 on 2020-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a text description, bla bla bla bla...'),
            preserve_default=False,
        ),
    ]
