# Generated by Django 3.0.4 on 2020-06-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200615_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='image/', width_field='width_field'),
        ),
    ]
