# Generated by Django 3.0.4 on 2020-06-16 18:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200616_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='image/'),
        ),
    ]
