# Generated by Django 3.0.4 on 2020-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200616_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default=300), null=True, upload_to='image/', width_field=models.IntegerField(default=500)),
        ),
    ]
