# Generated by Django 3.0.4 on 2020-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200616_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
