# Generated by Django 3.0.4 on 2020-06-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200617_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
