# Generated by Django 3.0.4 on 2020-06-30 03:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blogpost_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
    ]
