# Generated by Django 3.0.4 on 2020-06-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('payment', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('dept', models.CharField(choices=[('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('AE', 'Agricultural Engineering'), ('CHE', 'Chemical Engineering'), ('CS', 'Computer Science'), ('CTE', 'Computer Engineering'), ('SLT', 'Science Laboratory Technology'), ('FST', 'Food Science Technology'), ('PT', 'Pharmaceutical Technology'), ('DOP', 'Dispensary and Opticiary')], max_length=3, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
