# Generated by Django 3.0.4 on 2020-06-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200605_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='details',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile-pic.jpg', null=True, upload_to=''),
        ),
    ]
