# Generated by Django 3.0.4 on 2020-06-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200605_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('SET', 'School of Engineering Technology'), ('SIAS', 'School of Industrial and Applied Science'), ('SMT', 'School of Management Technology')], max_length=4, null=True)),
                ('faculty', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('SCIENCE', 'Science')], max_length=11, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.Details')),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ND_1', 'National Diploma 1'), ('ND_2', 'National Diploma 2'), ('HND_1', 'Higher National Diploma 1'), ('HND_2', 'Higher National Diploma 2')], max_length=5, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.Details')),
            ],
        ),
        migrations.CreateModel(
            name='CoursesRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_registered', models.CharField(choices=[('STATICS_MEC_101', 'Mechanical Engineering Science 1'), ('EEC_115', 'Electrical Engineering Science 1'), ('LOGIC_MTH_111', 'Logic and Linear Algebra'), ('MTH_101', 'Mathematics'), ('CALCULUS_MTH_201', 'Calculus'), ('TECHNICAL_DRAWING_MEC_102', 'Technical Drawing'), ('TECHNICAL_DRAWING_MEC_202', 'Technical Drawing'), ('MTH_202', 'Trigonometry'), ('EEC_201', 'Electrical Engineering Science 2'), ('STAT_101', 'Statistics'), ('PHY_101', 'Elementary Physics'), ('PHY_102', 'Atomic and Nuclear Physics'), ('CHEM_101', 'Inorganic Chemistry'), ('CHEM_102', 'Organic Chemistry'), ('BIO_101', 'Biology'), ('PMT_101', 'Pharmaceutical Calculation'), ('THERMO_MEC_203', 'Thermodynamics'), ('STRENGTH_MEC_222', 'Strength of Material'), ('FLUID_CEC_101', 'Fluid Mechanics'), ('STRUCTURAL_MECHANICS_CEC_101', 'Structural Mechanics')], max_length=28, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.Details')),
            ],
        ),
    ]
