# Generated by Django 3.0.4 on 2020-06-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_coursesregistered_levels_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesregistered',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='detail',
        ),
        migrations.AddField(
            model_name='details',
            name='courses_registered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.CoursesRegistered'),
        ),
        migrations.AddField(
            model_name='details',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.Levels'),
        ),
        migrations.AddField(
            model_name='details',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.Schools'),
        ),
    ]
