# Generated by Django 3.0.4 on 2020-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20200606_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='faculty',
            field=models.CharField(choices=[('ENGINEERING', 'Engineering'), ('SCIENCE', 'Science'), ('BUSINESS', 'Business')], max_length=11, null=True),
        ),
    ]
