# Generated by Django 3.0.4 on 2020-06-06 17:50

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20200606_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('SCIENCE', 'Science'), ('BUSINESS', 'Business')], max_length=11, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='schools',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='coursesregistered',
            name='subjects_registered',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MECHANICAL_ENGINEERING_SCIENCE_1', 'Mechanical Engineering Science 1'), ('ELECTRICAL_ENGINEERING_SCIENCE_1', 'Electrical Engineering Science 1'), ('LOGIC_AND_LINEAR_ALGEBRA', 'Logic and Linear Algebra'), ('MATHEMATICS', 'Mathematics'), ('CALCULUS', 'Calculus'), ('TECHNICAL_DRAWING_1', 'Technical Drawing 1'), ('TECHNICAL_DRAWING_2', 'Technical Drawing 2'), ('TRIGONOMETRY', 'Trigonometry'), ('ELECTRICAL_ENGINEERING_SCIENCE_2', 'Electrical Engineering Science 2'), ('STATISTICS', 'Statistics'), ('ELEMENTARY_PHYSICS', 'Elementary Physics'), ('ATOMIC_AND_NUCLEAR_PHYSIS', 'Atomic and Nuclear Physics'), ('INORGANIC_CHEMISTRY', 'Inorganic Chemistry'), ('ORGANIC_CHEMISTRY', 'Organic Chemistry'), ('BIOLOGY', 'Biology'), ('PHARMACEUTICAL_CALCULATION', 'Pharmaceutical Calculation'), ('THERMODYNAMICS', 'Thermodynamics'), ('STRENGTH_OF_MATERIAL', 'Strength of Material'), ('FLUID_MECHANICS', 'Fluid Mechanics'), ('STRUCTURAL_MECHANICS', 'Structural Mechanics')], max_length=399, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.Faculty'),
        ),
    ]
