# Generated by Django 3.0.4 on 2020-06-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20200606_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesregistered',
            options={'verbose_name_plural': 'CoursesRegistered'},
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name_plural': 'Details'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='levels',
            options={'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterModelOptions(
            name='schools',
            options={'verbose_name_plural': 'Schools'},
        ),
    ]
