# Generated by Django 3.0.4 on 2020-06-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_auto_20200606_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesregistered',
            name='subjects_registered',
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name='details',
            name='courses_registered',
        ),
        migrations.AddField(
            model_name='details',
            name='courses_registered',
            field=models.ManyToManyField(to='records.CoursesRegistered'),
        ),
    ]
